name: Deploy to S3

on:
  push:
    branches:
      - staging
      - main
  pull_request:
    branches:
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' 

    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Create .env file
      run: |
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          echo "REACT_APP_API_URL=${{ secrets.PROD_API_URL }}" >> .env
        else
          echo "REACT_APP_API_URL=${{ secrets.STAGING_API_URL }}" >> .env
        fi
        echo "REACT_APP_APP_ENV=production" >> .env
      env:
        PORT: 8002

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        args: --acl public-read --delete
      env:
        AWS_S3_BUCKET: ${{ github.ref == 'refs/heads/main' && 'dexai.app' || 'staging.dexai.app' }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: build
