export const PAYMENT_INITIAL_STATE = {
    isEdit: false,
    searchValue: '',
    modalInputValue: '',
    modalCheckboxDefaultPayment: false,
    modalInputPaymentRefName: '',
    prevInputValue: '',
    isLoading: false,
    isEmptyData: false,
    isFetchingData: true,
    isFocus: false,
    isHeaderPanel: false,
    isSearching: false,
    searchedItems: [],
    isContentLoading: false,
    selected: 0,
  };